[workspace]
# These binaries are built during `cargo dist` runs
members = [
  "rust/hash-checker",
  "rust/hash-checker-gui"
]

[package.hash-checker]
binaries = ["hash-checker"]

[package.hash-checker-gui]
binaries = ["hash-checker-gui"]
